import { describe, it, expect, afterAll } from 'vitest';
import { provisionDemoTenant, verifyLogin } from '../provisioningService.js';
import { withTenant } from '../../tenancy/withTenant.js';
import { closePools } from '../../tenancy/pool.js';
import { resolveActiveTenant } from '../../tenancy/admin.js';
import { getOverview } from '../../admin/adminService.js';
import { searchMentors } from '../../search/mentorSearch.js';

const hasDb = Boolean(process.env.DATABASE_URL && process.env.DIRECT_URL && process.env.AUTH_SECRET);
const rand = () => Math.random().toString(36).slice(2, 7);

describe.skipIf(!hasDb)('Tenant provisioning & demo environment (integration)', () => {
  afterAll(async () => {
    await closePools();
  });

  it('provisions a fully usable, navigable tenant from one call', async () => {
    const slug = `acme${rand()}`;
    const r = await provisionDemoTenant({ slug, name: 'Acme Demo' });

    expect(r.alreadyExisted).toBe(false);
    expect(r.counts).toMatchObject({ mentors: 3, mentees: 4, participants: 7, mentorships: 1, sessions: 1 });

    // Tenant resolves by host (no dev intervention needed afterwards).
    const res = await resolveActiveTenant(`${slug}.localhost`);
    expect(res.kind).toBe('TENANT');

    // Seeded admin can actually authenticate.
    const auth = await verifyLogin(`${slug}.localhost`, r.admin.email, r.password);
    expect(auth.role).toBe('admin');

    // Admin metrics are real and non-zero (data exists in the DB).
    const ov = await getOverview(r.tenant.id);
    expect(ov.users.active).toBeGreaterThanOrEqual(8);
    expect(ov.mentors.available).toBeGreaterThanOrEqual(3); // 3 mentors seeded available
    expect(ov.mentorships.active).toBe(1);
    expect(ov.sessions.total).toBe(1);

    // Mentor directory is non-empty (mentors available).
    const search = await searchMentors(r.tenant.id, {});
    expect(search.items.length).toBeGreaterThanOrEqual(3);

    // Default program has the seeded participants.
    const participants = await withTenant(r.tenant.id, (db) =>
      db.query<{ c: number }>(
        "SELECT count(*)::int AS c FROM program_participant WHERE status = 'active'",
      ),
    );
    expect(participants.rows[0]!.c).toBe(7);

    // Branding is explicitly configured (not relying on hidden defaults).
    const settings = await withTenant(r.tenant.id, (db) =>
      db.query<{ display_name: string }>('SELECT display_name FROM tenant_settings LIMIT 1'),
    );
    expect(settings.rows[0]?.display_name).toBe('Acme Demo');

    // Real notifications were generated by the seeded activity.
    const notes = await withTenant(r.tenant.id, (db) =>
      db.query<{ c: number }>('SELECT count(*)::int AS c FROM notification'),
    );
    expect(notes.rows[0]!.c).toBeGreaterThan(0);
  });

  it('is idempotent on slug (re-run does not duplicate)', async () => {
    const slug = `acme${rand()}`;
    await provisionDemoTenant({ slug });
    const again = await provisionDemoTenant({ slug });
    expect(again.alreadyExisted).toBe(true);
  });

  it('rejects reserved slugs', async () => {
    await expect(provisionDemoTenant({ slug: 'admin' })).rejects.toThrow();
  });

  it('keeps tenants isolated (A does not see B)', async () => {
    const a = `acme${rand()}`;
    const b = `acme${rand()}`;
    const ra = await provisionDemoTenant({ slug: a });
    const rb = await provisionDemoTenant({ slug: b });

    // B's tenant context cannot see A's seeded users.
    const cross = await withTenant(rb.tenant.id, (db) =>
      db.query<{ c: number }>('SELECT count(*)::int AS c FROM tenant_user WHERE email LIKE $1', [
        `%@${a}.demo`,
      ]),
    );
    expect(cross.rows[0]!.c).toBe(0);
    expect(ra.tenant.id).not.toBe(rb.tenant.id);
  });
});
